[project]
name = "unboil-fastapi-stripe"
version = "0.1.20"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "eyueldk" }
]
dependencies = [
    "fastapi>=0.100.0",
    "httpx>=0.20.0",
    "pydantic>=2.0.0",
    "pydantic-settings>=2.0.0",
    "sqlalchemy>=2.0.0",
    "stripe>=12.0.0",
    "unboil-utils-fastapi",
    "unboil-utils-sqlalchemy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
unboil-utils-fastapi = { git = "https://github.com/EyuelDK/unboil-fastapi.git", subdirectory = "unboil-utils-fastapi", rev = "b8c22555d3c893c8f230554ec039c19f336b89b0" }
unboil-utils-sqlalchemy = { git = "https://github.com/EyuelDK/unboil-fastapi.git", subdirectory = "unboil-utils-sqlalchemy", rev = "b8c22555d3c893c8f230554ec039c19f336b89b0" }
