name: Publish Python Package
on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    working-directory: ${{ inputs.working-directory }}
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/