name: Publish unboil-fastapi-auth
on:
  push:
    branches:
      - main
    paths:
      - unboil-fastapi-auth/**
  workflow_dispatch:
jobs:

  publish:
    uses: ./.github/workflows/publish.python.package.yml
    permissions:
      id-token: write
    secret: inherit
    with:
      working-directory: unboil-fastapi-auth
      environment-name: pypi
      environment-url: https://pypi.org/p/unboil-fastapi-auth

