name: Publish unboil-fastapi-auth
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:

  publish:
    uses: ./.github/workflows/publish.python.package.yml
    with:
      working-directory: unboil-fastapi-auth